apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-cron
            image: 'gcr.io/gcp-project/test-cron:latest'
            args:
            - ./simple_python_script.py
            command:
            - python
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Allow
